# Generated by Django 3.1.6 on 2021-02-20 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookbookapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredients',
            old_name='name',
            new_name='ingredientname',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='name',
            new_name='recipename',
        ),
    ]
