# Generated by Django 3.1.6 on 2021-02-20 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookbookapp', '0002_auto_20210220_0222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredients',
            old_name='ingredientname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='recipename',
            new_name='name',
        ),
    ]
