# Generated by Django 3.1.6 on 2021-02-21 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbookapp', '0003_auto_20210220_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredients',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ingredients',
            name='unit',
            field=models.CharField(default='g', max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
